[providers.node]
version = "18"

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm ci --only=production --no-audit"]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start -- --port $PORT"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"