# Multi-service deployment configuration
[[services]]
name = "frontend"
source = "."
buildCommand = "npm install --legacy-peer-deps && npm run build"
startCommand = "npm start"
variables = { NODE_ENV = "production", PORT = "3000" }

[[services]]
name = "backend"
source = "./backend"
buildCommand = "pip install -r requirements.txt"
startCommand = "uvicorn main:app --host 0.0.0.0 --port 8000"
variables = { PORT = "8000", PYTHONPATH = "/app" }