#!/bin/bash

echo "🚀 Deploy usando templates oficiais Railway/Vercel"
echo "=================================================="

echo ""
echo "📋 OPÇÕES DE DEPLOY:"
echo ""
echo "1️⃣  RAILWAY - Next.js + Supabase + Prisma + tRPC"
echo "   Template: https://railway.com/template/wj1mcU"
echo "   • Clique em 'Deploy Now'"
echo "   • Conecte seu GitHub"
echo "   • Railway configura automaticamente"
echo ""

echo "2️⃣  VERCEL - Supabase Starter"
echo "   Template: https://vercel.com/templates/next.js/supabase"
echo "   • Clique em 'Deploy'"
echo "   • Conecte GitHub + Supabase automaticamente"
echo "   • Vercel + Supabase Integration"
echo ""

echo "3️⃣  MANUAL - Clonar template Vercel"
echo "   Comando: npx create-next-app --example with-supabase agentes-conversao"
echo ""

echo "🔧 VARIÁVEIS DE AMBIENTE NECESSÁRIAS:"
echo "======================================"
echo "✅ NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL"
echo "✅ NEXT_PUBLIC_SUPABASE_ANON_KEY=[configurada]"
echo "✅ SUPABASE_SERVICE_ROLE_KEY=[configurada]"
echo "✅ NEXTAUTH_SECRET=$NEXTAUTH_SECRET"
echo "✅ GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID"
echo ""

echo "💡 RECOMENDAÇÃO:"
echo "==============="
echo "Use a OPÇÃO 2 (Vercel) para melhor integração!"
echo ""
echo "🎯 Próximos passos:"
echo "1. Acesse: https://vercel.com/templates/next.js/supabase"
echo "2. Clique em 'Deploy'"
echo "3. Conecte seu GitHub"
echo "4. As variáveis do Supabase serão configuradas automaticamente"
echo "5. Merge o código do seu projeto atual após o deploy"
echo ""

echo "🔗 Links úteis:"
echo "• Railway Template: https://railway.com/template/wj1mcU"
echo "• Vercel Template: https://vercel.com/templates/next.js/supabase"
echo "• Demo funcionando: https://demo-nextjs-with-supabase.vercel.app/"